Repository dolbyio-samples/rts-app-react-publisher-viewer, pull requests merged in 2023-03, with the labels that each got.

#352 solved #284 and #248
  apps/viewer/src/app.tsx
  package.json
  yarn.lock
Labels: CLA Signed

#351 Update read me and add missing files
  README.md
  additional-configurations.md
  apps/viewer/.env.example
  docs/img/setup_create_new.png
  docs/img/tokens.png
Labels: CLA Signed

#354 Issue 353 viewer issues when source name empty
  libs/use-multi-media-streams/src/utils.ts
  libs/use-publisher/src/index.ts
  libs/use-viewer/src/index.ts
Labels: CLA Signed

#357 Issue 349 delayed rerendering when changing quality in viewer
  apps/viewer/src/app.tsx
Labels: CLA Signed

#356 Issue 323 can not stream local file in safari
  apps/publisher/src/app.tsx
  apps/publisher/src/hooks/useCanCaptureStream.ts
Labels: CLA Signed

#359 Update dashboard photo
  docs/img/tokens.png
Labels: documentation

#361 Issue 360 handle empty source name in dolby.io broadcast app
  apps/e2e-test/src/reporter/cucumber-report.ts
  apps/e2e-test/src/steps/app-specific/workflow/workflow.data.ts
  apps/publisher/vite.config.ts
  apps/viewer/src/app.tsx
  apps/viewer/vite.config.ts
  libs/use-viewer/src/index.ts
  libs/use-viewer/src/types.ts
  libs/use-viewer/src/utils.ts
  package.json
Labels: bug, CLA Signed

#362 Issue 318 do not persist preview mediastream constraints to stream tile
  libs/device-selection/src/index.tsx
Labels: bug, CLA Signed

#366 Issue 274 separate use multi media streams hook responsibilities
  .storybook/main.ts
  apps/publisher/src/app.tsx
  apps/publisher/src/components/publisher-video-view/index.tsx
  apps/publisher/src/components/publisher-video-view/types.ts
  apps/publisher/src/components/publisher-video-view/video-control-bar/index.tsx
  apps/publisher/src/components/publisher-video-view/video-control-bar/settings-popover/types.ts
  apps/publisher/src/hooks/use-can-capture-stream/index.ts
  apps/publisher/src/hooks/use-multi-media-streams/constants.ts
  apps/publisher/src/hooks/use-multi-media-streams/index.ts
  apps/publisher/src/hooks/use-multi-media-streams/reducer.ts
  apps/publisher/src/hooks/use-multi-media-streams/types.ts
  apps/publisher/src/hooks/use-multi-media-streams/utils.ts
  apps/stories/src/useLocalFile.stories.tsx
  apps/stories/src/useMultiMediaStreams.stories.tsx
  libs/use-local-file/.gitkeep
  libs/use-local-file/src/index.ts
  libs/use-local-files/.eslintrc.json
  libs/use-local-files/project.json
  libs/use-local-files/src/index.ts
  libs/use-local-files/src/types.ts
  libs/use-local-files/src/vite-env.d.ts
  libs/use-local-files/tsconfig.json
  libs/use-local-files/tsconfig.lib.json
  libs/use-media-devices/.eslintrc.json
  libs/use-media-devices/project.json
  libs/use-media-devices/src/constants.ts
  libs/use-media-devices/src/index.ts
  libs/use-media-devices/src/types.ts
  libs/use-media-devices/src/utils.ts
  libs/use-media-devices/src/vite-env.d.ts
  libs/use-media-devices/tsconfig.json
  libs/use-media-devices/tsconfig.lib.json
  libs/use-multi-media-streams/.gitkeep
  libs/use-multi-media-streams/src/index.ts
  libs/use-multi-media-streams/src/utils.ts
  libs/use-screen-share/.eslintrc.json
  libs/use-screen-share/project.json
  libs/use-screen-share/src/index.ts
  libs/use-screen-share/src/types.ts
  libs/use-screen-share/src/vite-env.d.ts
  libs/use-screen-share/tsconfig.json
  libs/use-screen-share/tsconfig.lib.json
  tsconfig.base.json
Labels: CLA Signed

#365 Update .env.example
  apps/viewer/.env.example
Labels: CLA Signed

#364 Update .env.example
  apps/publisher/.env.example
Labels: CLA Signed

#368 Issue 367 implement dolby webrtc statistics library
  apps/publisher/src/components/publisher-video-view/types.ts
  apps/publisher/src/components/publisher-video-view/video-control-bar/types.ts
  apps/viewer/src/components/viewer-video-view/types.ts
  apps/viewer/src/components/viewer-video-view/video-control-bar/types.ts
  libs/statistics-popover/src/components/statistics-info/index.tsx
  libs/statistics-popover/src/components/statistics-info/types.ts
  libs/statistics-popover/src/components/statistics-info/utils.ts
  libs/statistics-popover/src/index.tsx
  libs/statistics-popover/src/types.ts
  libs/use-publisher/src/index.ts
  libs/use-publisher/src/types.ts
  libs/use-viewer/src/index.ts
  libs/use-viewer/src/types.ts
  libs/video-view/src/types.ts
  millicast-sdk.d.ts
  package.json
  yarn.lock
Labels: CLA Signed
