Repository dolbyio-samples/rts-app-react-publisher-viewer, pull requests merged in 2023-02, with the labels that each got.

#279 Issue 241 refactor publisher streams states
  apps/e2e-test/features/publisher-camera-stream.feature
  apps/e2e-test/features/publisher-preview.feature
  apps/e2e-test/src/steps/app-specific/workflow/workflow.data.ts
  apps/publisher/src/app.tsx
  apps/publisher/src/hooks/use-camera-capabilities.ts
  apps/publisher/tsconfig.json
  apps/stories/src/useMultiMediaStreams.stories.tsx
  apps/viewer/src/app.tsx
  libs/device-selection/src/index.tsx
  libs/use-local-file/src/index.ts
  libs/use-local-file/src/types.ts
  libs/use-multi-media-streams/src/constants.ts
  libs/use-multi-media-streams/src/index.ts
  libs/use-multi-media-streams/src/reducer.ts
  libs/use-multi-media-streams/src/types.ts
  libs/use-multi-media-streams/src/utils.ts
  libs/use-multi-media-streams/tsconfig.lib.json
  libs/use-publisher/src/constants.ts
  libs/use-publisher/src/index.ts
  libs/use-publisher/src/reducer.ts
  libs/use-publisher/src/types.ts
  libs/use-viewer/src/index.ts
  libs/use-viewer/src/reducer.ts
  libs/use-viewer/src/types.ts
Labels: CLA Signed

#280 Issue 253 bdd scenarios screen sharing
  apps/e2e-test/features/publisher-camera-stream.feature
  apps/e2e-test/features/publisher-screen-stream.feature
  apps/e2e-test/project.json
  apps/e2e-test/selector-mappings/components/stream-views.yaml
  apps/e2e-test/selector-mappings/pages/preview.yaml
  apps/e2e-test/selector-mappings/pages/stream.yaml
  apps/e2e-test/selector-mappings/pages/viewer.yaml
  apps/e2e-test/selector-mappings/pages/waiting-room.yaml
  apps/e2e-test/src/playwright-support/app-specific/element-read.ts
  apps/e2e-test/src/steps/app-specific/action.step.ts
  apps/e2e-test/src/steps/app-specific/verification.step.ts
  apps/e2e-test/src/steps/app-specific/workflow/workflow.data.ts
  apps/e2e-test/src/steps/app-specific/workflow/workflow.ts
  apps/e2e-test/src/steps/app-specific/workflow/workflow.utils.ts
  apps/e2e-test/src/steps/generic/navigation.step.ts
  apps/e2e-test/src/steps/generic/utils.ts
Labels: CLA Signed, QA

#276 Update readme with multi screen
  .github/workflows/bdd-tests.yml
  .github/workflows/ci-cd.yml
  README.md
  apps/e2e-test/README.md
  apps/e2e-test/scripts/auto_utils.sh
  apps/e2e-test/src/config/defaults.ts
  apps/publisher/index.html
  apps/publisher/src/app.tsx
  apps/publisher/src/vite-env.d.ts
  apps/viewer/index.html
  apps/viewer/src/app.tsx
  apps/viewer/src/vite-env.d.ts
  docs/img/banner.jpeg
  docs/img/env.png
  docs/img/permissions.png
  docs/img/tokens.png
Labels: documentation, CLA Signed

#297 Replace Millicast with RTS in docs
  .github/workflows/bdd-tests.yml
  .github/workflows/ci-cd.yml
  README.md
  apps/publisher/index.html
  apps/publisher/src/app.tsx
  apps/publisher/src/vite-env.d.ts
  apps/viewer/index.html
  apps/viewer/src/components/content.tsx
  apps/viewer/src/vite-env.d.ts
Labels: CLA Signed

#298 only show close button for each source when there are more than 1 sources
  apps/publisher/src/app.tsx
  apps/publisher/src/components/publisher-video-view/index.tsx
  apps/publisher/src/components/publisher-video-view/types.ts
Labels: CLA Signed

#299 Update README.md
  README.md
Labels: CLA Signed

#293 Feedback on testing
  README.md
  apps/e2e-test/README.md
  apps/publisher/.env.example
  docs/img/env.png
Labels: CLA Signed

#302 V1 read me update
  README.md
  docs/img/banner.jpeg
  docs/img/env.png
  docs/img/permissions.png
  docs/img/tokens.png
Labels: CLA Signed

#304 show video or audio statistics
  libs/use-viewer/src/reducer.ts
Labels: CLA Signed

#308 [Bugfix] Viewer video freeze after remove publisher source
  libs/use-viewer/src/index.ts
  libs/use-viewer/src/utils.ts
Labels: CLA Signed

#303 style: fixed safari styles
  apps/viewer/src/app.tsx
  libs/video-view/src/index.tsx
  libs/video-view/src/types.ts
Labels: CLA Signed

#309 Issue 284 video in viewer freezes with large bitrate resolution changes in publisher
  apps/viewer/src/app.tsx
  libs/use-viewer/src/index.ts
  libs/use-viewer/src/types.ts
  libs/use-viewer/src/utils.ts
Labels: CLA Signed

#312 [Bugfix] Issue 285 filter invalid statistics
  libs/statistics-popover/src/index.tsx
Labels: CLA Signed

#317 [Bugfix] Cannot open publisher in Safari
  apps/publisher/src/app.tsx
Labels: CLA Signed

#310 issue 307 swap main and secondary videos instead of mirroring in viewer
  apps/viewer/src/app.tsx
  libs/use-viewer/src/index.ts
  libs/use-viewer/src/types.ts
  libs/use-viewer/src/utils.ts
Labels: CLA Signed

#320 [Bugfix] remove device change event handler
  libs/use-multi-media-streams/src/index.ts
Labels: CLA Signed

#327 Issue 326 stream stats in viewer regression
  apps/viewer/src/app.tsx
  libs/use-viewer/src/index.ts
  libs/use-viewer/src/reducer.ts
  libs/use-viewer/src/types.ts
  libs/use-viewer/src/utils.ts
Labels: CLA Signed

#305 Issue 283 fix tests: Fix camera preview and streaming test failures
  .github/workflows/ci-cd.yml
  apps/e2e-test/features/local-scenario.feature
  apps/e2e-test/features/publisher-camera-preview.feature
  apps/e2e-test/features/publisher-camera-stream.feature
  apps/e2e-test/features/publisher-preview.feature
  apps/e2e-test/features/publisher-screen-preview.feature
  apps/e2e-test/features/publisher-screen-stream.feature
  apps/e2e-test/features/viewer-waiting.feature
  apps/e2e-test/project.json
  apps/e2e-test/selector-mappings/components/common-components.yaml
  apps/e2e-test/selector-mappings/components/settings.yaml
  apps/e2e-test/selector-mappings/components/stream-views.yaml
  apps/e2e-test/selector-mappings/pages/publisher-streaming.yaml
  apps/e2e-test/selector-mappings/pages/viewer-streaming.yaml
  apps/e2e-test/src/hooks/utils.ts
  apps/e2e-test/src/playwright-support/app-specific/element-read.ts
  apps/e2e-test/src/playwright-support/app-specific/element-verification.ts
  apps/e2e-test/src/playwright-support/generic/element-action.ts
  apps/e2e-test/src/playwright-support/generic/verification.ts
  apps/e2e-test/src/steps/app-specific/action.step.ts
  apps/e2e-test/src/steps/app-specific/navigation.step.ts
  apps/e2e-test/src/steps/app-specific/verification.step.ts
  apps/e2e-test/src/steps/app-specific/workflow/workflow.data.ts
  apps/e2e-test/src/steps/app-specific/workflow/workflow.ts
  apps/e2e-test/src/steps/app-specific/workflow/workflow.utils.ts
  apps/e2e-test/src/steps/generic/action.step.ts
  apps/e2e-test/src/steps/generic/utils.ts
  apps/e2e-test/src/steps/generic/verification.step.ts
  apps/publisher/project.json
  apps/publisher/src/app.tsx
  apps/viewer/project.json
  apps/viewer/src/app.tsx
  package.json
  yarn.lock
Labels: CLA Signed, QA

#322 feat: individual video playback control states in viewer app
  apps/e2e-test/features/publisher-camera-preview.feature
  apps/e2e-test/features/publisher-camera-stream.feature
  apps/e2e-test/features/publisher-screen-preview.feature
  apps/e2e-test/features/publisher-screen-stream.feature
  apps/e2e-test/src/steps/app-specific/workflow/workflow.data.ts
  apps/viewer/src/app.tsx
  apps/viewer/src/components/viewer-video-view/index.tsx
  apps/viewer/src/components/viewer-video-view/types.ts
  apps/viewer/src/hooks/use-playback-control/index.ts
  apps/viewer/src/hooks/use-playback-control/types.ts
  libs/statistics-popover/src/components/statistics-info/constants.ts
  libs/statistics-popover/src/components/statistics-info/utils.ts
  libs/use-publisher/src/constants.ts
Labels: CLA Signed

#329 Issue 328 handle update quality options for main stream only
  apps/viewer/src/app.tsx
  libs/use-viewer/src/index.ts
  libs/use-viewer/src/reducer.ts
  libs/use-viewer/src/types.ts
  libs/use-viewer/src/utils.ts
Labels: CLA Signed

#330 Issue 314 handle empty audio tracks
  libs/use-viewer/src/utils.ts
Labels: CLA Signed

#336 Issue 335 removed deprecated dispatch in useViewer
  libs/use-viewer/src/index.ts
Labels: CLA Signed

#331 Issue 301 control bar tweaks in publisher and viewer
  apps/e2e-test/features/publisher-screen-preview.feature
  apps/publisher/src/components/publisher-video-view/video-control-bar/index.tsx
  apps/publisher/src/components/publisher-video-view/video-control-bar/settings-popover/index.tsx
  apps/viewer/src/components/viewer-video-view/index.tsx
  apps/viewer/src/components/viewer-video-view/video-control-bar/index.tsx
  apps/viewer/src/components/viewer-video-view/video-control-bar/settings-popover/index.tsx
  apps/viewer/src/components/viewer-video-view/video-control-bar/types.ts
  libs/popover/src/index.tsx
  libs/popover/src/types.ts
  libs/statistics-popover/src/index.tsx
Labels: CLA Signed

#340 Issue 243 hidden viewer link and optimize tests
  .github/workflows/ci-cd.yml
  apps/e2e-test/features/publisher-local-file-preview.feature
  apps/e2e-test/project.json
  apps/e2e-test/selector-mappings/components/header-footer.yaml
  apps/e2e-test/src/hooks/hooks.ts
  apps/e2e-test/src/playwright-support/app-specific/browser-actions.ts
  apps/e2e-test/src/playwright-support/generic/element-verification.ts
  apps/e2e-test/src/steps/app-specific/navigation.step.ts
  apps/e2e-test/src/steps/app-specific/workflow/workflow.utils.ts
  apps/e2e-test/src/utils/selector-mapper.ts
  apps/publisher/project.json
  apps/publisher/src/app.tsx
  nx.json
  package.json
  yarn.lock
Labels: CLA Signed, QA

#342 Issue 338 update audio toggle behaviour
  apps/viewer/src/components/viewer-video-view/index.tsx
  apps/viewer/src/hooks/use-playback-control/index.ts
Labels: CLA Signed

#341 Issue 339 update quality options when changing simulcast
  apps/e2e-test/features/publisher-camera-stream.feature
  apps/e2e-test/features/publisher-local-file-stream.feature
  apps/e2e-test/features/publisher-screen-stream.feature
  libs/use-viewer/src/index.ts
  libs/use-viewer/src/utils.ts
Labels: CLA Signed

#344 Issue 343 Github - Execute Test Jobs In Parallel
  .github/actions/setup/action.yml
  .github/workflows/ci-cd.yml
  .github/workflows/test-suite.yml
  apps/e2e-test/features/multisource.feature
  apps/e2e-test/features/publisher-camera-stream.feature
  apps/e2e-test/features/publisher-local-file-stream.feature
  apps/e2e-test/features/publisher-screen-stream.feature
  apps/e2e-test/project.json
  apps/e2e-test/src/hooks/ScenarioWorld.ts
  apps/publisher/project.json
Labels: CLA Signed

#350 Always deploy the publisher and viewer
  .github/workflows/ci-cd.yml
Labels: CLA Signed

#347 Issue 296 screen share stream in viewer stuck on loading
  apps/viewer/src/components/content.tsx
Labels: CLA Signed
